version: '3.8'
services:
  neo4j:
    image: neo4j:5.12-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/aeclaudemax
    volumes:
      - ./neo4j-data:/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  airflow:
    image: apache/airflow:slim
    ports:
      - "8089:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow-dags:/opt/airflow/dags
      - ./dev-docs:/opt/airflow/dev-docs
    command: standalone
